languaje: node_js
node_js:
    - "8"
install:
    - node -v
    - npm -v
    - npm install
script:
    - npm run build
deploy:
    provider: firebase
    token: $FIREBASE_TOKEN
    project: somoFilms.com
