node ../scripts/owget/index.js -i ../docs/works-urls/akelarre.txt -o ./akelarre
node ../scripts/owget/index.js -i ../docs/works-urls/arima.txt -o ./arima
node ../scripts/owget/index.js -i ../docs/works-urls/gecko.txt -o ./gecko
node ../scripts/owget/index.js -i ../docs/works-urls/hdedon.txt -o ./hdedon
node ../scripts/owget/index.js -i ../docs/works-urls/regis.txt -o ./regis
node ../scripts/owget/index.js -i ../docs/works-urls/torralbenc.txt -o ./torralbenc
node ../scripts/owget/index.js -i ../docs/works-urls/totem.txt -o ./totem
node ../scripts/owget/index.js -i ../docs/works-urls/urso.txt -o ./urso
node ../scripts/owget/index.js -i ../docs/works-urls/viura.txt -o ./viura
