node scripts/resizer/index.js -i ./resources/akelarre -o ./src/assets/img/works/photo/akelarre -w 200 --nt akelarre_small
node scripts/resizer/index.js -i ./resources/arima -o ./src/assets/img/works/photo/arima -w 200 --nt arima_smal
node scripts/resizer/index.js -i ./resources/gecko -o ./src/assets/img/works/photo/gecko -w 200 --nt gecko_small
node scripts/resizer/index.js -i ./resources/hdedon -o ./src/assets/img/works/photo/hdedon -w 200 --nt hdedon_small
node scripts/resizer/index.js -i ./resources/regis -o ./src/assets/img/works/photo/regis -w 200 --nt regis_small
node scripts/resizer/index.js -i ./resources/torralbenc -o ./src/assets/img/works/photo/torralbenc -w 200 --nt torralbenc_small
node scripts/resizer/index.js -i ./resources/totem -o ./src/assets/img/works/photo/totem -w 200 --nt totem_small
node scripts/resizer/index.js -i ./resources/urso -o ./src/assets/img/works/photo/urso -w 200 --nt urso_small
node scripts/resizer/index.js -i ./resources/viura -o ./src/assets/img/works/photo/viura -w 200 --nt viura_small
